---
title: "STA141C Final Project"
author: "Xiaoxuan Hu"
date: "3/15/2021"
output: html_document
---

```{r}
library(blblm)
```

```{r}
library(devtools)
```

```{r,paged.print = FALSE, warning=FALSE}
#blblm() with and without parallelization
library(blblm)
library(furrr)
fit1 = blblm(mpg ~ wt * hp, data = mtcars, parallel = TRUE, nthread = 4)
coef(fit1)

fit2 = blblm(mpg ~ wt * hp, data = mtcars)
coef(fit2)

```


```{r,paged.print = FALSE, warning=FALSE}
library(blblm)
#blblm() with and without parallelization
bench::mark(blblm(mpg ~ wt * hp, data = mtcars, m = 10, B = 10000, parallel = TRUE,nthread = 4), blblm(mpg ~ wt * hp, data = mtcars, m = 10, B = 10000), check = FALSE)
```

```{r}
library(blblm)
library(ISLR)
library(future)
plan(multiprocess, workers = 4)
blblogreg(Direction ~ Lag1 + Lag2, data = Smarket, m = 3, B = 100, parallel = TRUE)

fit = blblogreg(Direction ~ Lag1 + Lag2 + Volume, data = Smarket, m = 10, B = 10000, parallel = TRUE)

blblogreg(Direction ~ Lag1 + Lag2, data = Smarket, m = 3, B = 100, parallel = TRUE)
```

